export const INIT_MOCKUP_DATA = "INIT_MOCKUP_DATA";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS"; 
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"; 
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR"; 

export const CREATE_PRODUCTS = "CREATE_PRODUCTS"; 
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS"; 
export const CREATE_PRODUCTS_ERROR = "CREATE_PRODUCTS_ERROR"; 

export const PRODUCT_UPLOAD_START = "PRODUCT_UPLOAD_START";
export const PRODUCT_DATA_PREPARED = "PRODUCT_DATA_PREPARE";
export const PRODUCT_UPLOADED = "PRODUCT_UPLOADED";
export const PRODUCT_UPLOAD_ERROR = "PRODUCT_UPLOAD_ERROR";


